---
title: "Create descriptive tables and figures"
author: "Kate Tran"
date: "2023-05-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tableone)
library(ggplot2)
library(ggstatsplot)
library(ggeffects)
library(ggsignif)
library(sjPlot)
library(lme4)

source("../utility_fun.R")
```

```{r}
dataset_main <- read_csv("../outputs/dataset_main_analysis_2y.csv")
```

# Correlation plots
```{r}
## 1.	AL, and 8 components of AL, age (Figure 2B)
pdf("../plots/correlation_AL_subcomponents_age.pdf", width = 7, height = 5)
cor_vars_AL_subcomp_age <- dataset_main %>% 
  select(
    `Allostatic Load` = allostatic_load,
    `Cholesterol` = biospec_blood_cholesterol,
    `HDL cholesterol` = biospec_blood_hdl_cholesterol,
    `Systolic blood pressure` = blood_pressure_sys_mean,
    `Diastolic blood pressure` = blood_pressure_dia_mean,
    `Waist (cm)` = anthro_waist_cm,
    `BMI` = bmi_percentiles,
    `DHEA` = hormone_scr_dhea_mean,
    `Hemoglobin A1C` = biospec_blood_hemoglobin_a1,
    `Age (years)` = age_years
  )
# cor_vars_AL_subcomp_age[,2:9] = winsor(cor_vars_AL_subcomp_age[,2:9],trim=0.01) (SF1)
plot_cor(cor_vars_AL_subcomp_age, pch.cex = 0.7, tl.cex = 0.7, cl.cex = 0.7, cl.ratio = 0.4)

dev.off()

## 2.	PRS separately for EUR (4 PRSs) and AFR (3 PRSs)
### Among EUR
pdf("../plots/correlation_PRS_EUR.pdf", width = 3, height = 2)
cor_vars_PRS_EUR <- dataset_main %>%
  filter(genetic_afr == 0) %>% 
  select(
    `Diabetes PRS` = T2D_fromEUR_PRS,
    `BMI PRS` = BMI_PRS,
    `Major Depressive Disorder PRS` = MDD_PRS,
    `PTSD PRS` = PTSD_fromEUR_PRS
  )
plot_cor(cor_vars_PRS_EUR, pch.cex = 0.4, tl.cex = 0.4, cl.cex = 0.4, cl.ratio = 0.3)
dev.off()

```

# Table 1
```{r}
# Among whole population
# Check if whole cohort at 2y in table 1 or those in the models
vars <- dataset_main %>% select(age_years, matches("race|_hisp$|sex")) %>% names()

vars_factor <- dataset_main %>% select(sex_br, matches("race|_hisp$")) %>% names()

write.csv(print(
  CreateTableOne(
    data = dataset_main,
    vars = vars,
    factorVars = vars_factor,
    includeNA = T,
    addOverall = T
  ),
  catDigits = 2,
  conDigits = 2), 
  "../outputs_paper/table1_091423.csv")
```

```{r}
dataset_main <- dataset_main %>%
    mutate(
        race = case_when(
            ethnicity_hisp == 0 & race_black == 1 ~ "NH-Black",
            ethnicity_hisp == 0 & race_white == 1 ~ "NH-White",
            ethnicity_hisp == 1 ~ "Hispanic",
            TRUE ~ NA_character_
        ),
        race = factor(race, c("NH-Black", "NH-White", "Hispanic")),
        
        sex_br = recode(sex_br, `0` = "Male", `1` = "Female"),
        sex_br = factor(sex_br, c("Female", "Male")))
```

```{r}
# Figure 3A
## Scatterplot between exposome and allostatic load
theme_set(theme_bw() +
            theme(axis.text.x = element_text(lineheight = 20, color = "black", face = "bold"),
                  axis.text.y = element_text(lineheight = 20, color = "black", face = "bold"),
                  axis.title.x = element_text(lineheight = 20, color = "black", face = "bold"),
                  axis.title.y = element_text(lineheight = 20, color = "black", face = "bold"),
                  axis.ticks = element_line(size = 0.5),
                  legend.text = element_text(lineheight = 20,  color = "black"),
                  legend.title = element_text(lineheight = 20, color = "black", face = "bold")))

ggplot(dataset_main, aes(x = exposome_score_1y, y = allostatic_load)) +  
  geom_point(color = "darkslategray4", alpha = 0.5) +
  geom_smooth(method = "lm", se = TRUE, color = "red") +
  labs(x = "Exposomic Score",
       y = "Allostatic Load")

ggsave(filename = "../plots/scatterplot_AL_exposome.pdf", width = 7, height = 4)


# Figure 3C
# Differential effects of sex and race between X Exposome and Y AL

## Stratified by sex
ggplot(dataset_main %>% filter(!is.na(sex_br)), #%>% rename("Sex" = sex_br), 
                 aes(x=exposome_score_1y, y=allostatic_load, color=sex_br, fill = sex_br)) +
    geom_smooth(method = lm, se = TRUE, fullrange = TRUE)+
    scale_color_manual(values = c("#1B9E77", "#D95F02")) +
    scale_fill_manual(values = c("#1B9E77", "#D95F02")) +
  labs(x = "Exposomic Score",
       y = "Allostatic Load (Z score)") +
  theme(legend.position = c(0.15, 0.8))

ggsave(filename = "../plots/scatterplot_AL_exposome_by_sex.pdf", width = 7, height = 5)

## Stratified by race
ggplot(dataset_main %>% filter(!is.na(race)), #%>% rename("Race" = race), 
       aes(x=exposome_score_1y, y=allostatic_load, color=race, fill = race)) +
  geom_smooth(method = lm, se = TRUE, fullrange = TRUE)+
  scale_color_manual(values = c("#E41A1C", "#377EB8", "#4DAF4A")) +
  scale_fill_manual(values = c("#E41A1C", "#377EB8", "#4DAF4A")) +
  labs(x = "Exposomic Score",
       y = "Allostatic Load (Z score)") +
  theme(legend.position = c(0.18, 0.75))

ggsave(filename = "../plots/scatterplot_AL_exposome_by_race.pdf", width = 7, height = 5)
```

Statistics for interaction
```{r}
covs <- c("age_years", "race_white", "race_black", "ethnicity_hisp", "sex_br", "household_income",  "highschool_diploma", "post_highschooler_education", "bachelor", "master_above")
random_effects <- "(1 | site_id_l_br/rel_family_id)"


tab_model(lmer(paste0("allostatic_load ~ sex_br*exposome_score_1y + ", paste(covs, collapse = " + "), "+", random_effects)
                  , data = dataset_main)) #significant 

tab_model(lmer(paste0("allostatic_load ~ race_black*exposome_score_1y + ", paste(covs, collapse = " + "), "+", random_effects)
                 , data = dataset_main)) # interaction not significant

tab_model(lmer(paste0("allostatic_load ~ ethnicity_hisp*exposome_score_1y + ", paste(covs, collapse = " + "), "+", random_effects)
        , data = dataset_main)) # interaction not significant
```

```{r}
# Firgure 3B
## Allostatic load
## BY SEX (B1)
### Get p-value
wilcox.test(allostatic_load ~ sex_br, dataset_main %>% filter(!is.na(sex)))$p.value #0.002995456

dataset_main %>% group_by(sex_br) %>% summarise(median = median(allostatic_load))
rcompanion::wilcoxonRG(x = as.numeric(dataset_main$allostatic_load), g = as.factor(dataset_main$sex_br), verbose=TRUE) #0.0484

ggbetweenstats(
  data = dataset_main %>% filter(!is.na(sex_br)),
  x = sex_br,
  y = allostatic_load,
  type = "nonparametric",
  plot.type = "box",
  # pairwise.comparisons = FALSE,
  centrality.plotting = FALSE,
  bf.message = FALSE,
  xlab = element_blank(),
  ylab = "Allostatic load (Z score)",
  violin.args = list(width = 0),
  palette = "Dark2",
  results.subtitle = FALSE) + 
  scale_y_continuous(breaks = seq(-2, 6, 2)) +
  geom_signif(
    comparisons = list(c("Female", "Male")),
    map_signif_level = TRUE, textsize = 8,
    y_position = 4,
    vjust = 0.5
  ) +
  theme(axis.text.x = element_text(size = 18, color = "black", face = "bold"),
        axis.text.y = element_text(size = 18, color = "black", face = "bold"),
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 18))

ggsave(filename = "../plots/AL_by_sex_boxplot.pdf")



dataset_main %>% group_by(race) %>% summarise(median = median(allostatic_load))

kruskal.test(allostatic_load ~ race, dataset_main)
FSA::dunnTest(allostatic_load ~ race,
              data = dataset_main %>% 
                mutate(allostatic_load = as.numeric(allostatic_load)),
              method = "holm")$res

ggbetweenstats(
  data = dataset_main %>% filter(!is.na(race)),
  x = race,
  y = allostatic_load,
  type = "nonparametric",
  plot.type = "box",
  pairwise.comparisons = FALSE,
  pairwise.display = "none",
  centrality.plotting = FALSE,
  bf.message = FALSE,
  xlab = element_blank(),
  ylab = element_blank(),
  violin.args = list(width = 0),
  palette = "Set1",
  results.subtitle = FALSE) +
  geom_signif(
    comparisons = list(c("NH-Black", "Hispanic"), c("NH-Black", "NH-White"), c("NH-White", "Hispanic")),
    map_signif_level = TRUE, textsize = 6,
    y_position = c(6, 5, 7),
    vjust = 0.1
  ) +
  scale_y_continuous(breaks = seq(0, 6, 2)) +
  theme(axis.text.x = element_text(size = 18, color = "black", face = "bold"),
        axis.text.y = element_text(size = 18, color = "black", face = "bold"),
        legend.text = element_text(size = 18))

ggsave(filename = "../plots/AL_by_race_boxplot_space.pdf")
```

# Figure 4 - Diabetes and MDD
```{r}
# among EUR
# 1SD + mean high PRS/ -1SD-mean low PRS: plot exposome and AL stratified by PRS
# 1SD + mean high PRS/ -1SD-mean low PRS/average btw 1SD and -1SD: plot exposome and AL stratified by PRS

# classify PRS
## BMI
mean(dataset_main$BMI_PRS[dataset_main$genetic_afr == 0], na.rm = T) - sd(dataset_main$BMI_PRS[dataset_main$genetic_afr == 0], na.rm = T)
mean(dataset_main$BMI_PRS[dataset_main$genetic_afr == 0], na.rm = T) + sd(dataset_main$BMI_PRS[dataset_main$genetic_afr == 0], na.rm = T)

## Diabetes
mean(dataset_main$T2D_fromEUR_PRS[dataset_main$genetic_afr == 0], na.rm = T) - sd(dataset_main$T2D_fromEUR_PRS[dataset_main$genetic_afr == 0], na.rm = T)
mean(dataset_main$T2D_fromEUR_PRS[dataset_main$genetic_afr == 0], na.rm = T) + sd(dataset_main$T2D_fromEUR_PRS[dataset_main$genetic_afr == 0], na.rm = T)

# Major Depressive Disorder (MDD) # EUR
mean(dataset_main$MDD_PRS[dataset_main$genetic_afr == 0], na.rm = T) - sd(dataset_main$MDD_PRS[dataset_main$genetic_afr == 0], na.rm = T)
mean(dataset_main$MDD_PRS[dataset_main$genetic_afr == 0], na.rm = T) + sd(dataset_main$MDD_PRS[dataset_main$genetic_afr == 0], na.rm = T)

# Cross Disorder (CDG2) # EUR
mean(dataset_main$newCDG2_PRS[dataset_main$genetic_afr == 0], na.rm = T) - sd(dataset_main$newCDG2_PRS[dataset_main$genetic_afr == 0], na.rm = T)
mean(dataset_main$newCDG2_PRS[dataset_main$genetic_afr == 0], na.rm = T) + sd(dataset_main$newCDG2_PRS[dataset_main$genetic_afr == 0], na.rm = T)

# PTSD_fromEUR_PRS
mean(dataset_main$PTSD_fromEUR_PRS[dataset_main$genetic_afr == 0], na.rm = T) - sd(dataset_main$PTSD_fromEUR_PRS[dataset_main$genetic_afr == 0], na.rm = T)
mean(dataset_main$PTSD_fromEUR_PRS[dataset_main$genetic_afr == 0], na.rm = T) + sd(dataset_main$PTSD_fromEUR_PRS[dataset_main$genetic_afr == 0], na.rm = T)
```

```{r}
dataset_main_eur <- dataset_main %>% filter(genetic_afr == 0) %>% 
  mutate(BMI_PRS_bins = cut(BMI_PRS, breaks = c(min(BMI_PRS, na.rm = T), -1.018603, 1.025242, max(BMI_PRS, na.rm = T))), #min, mean-1sd, mean+1sd, max
         BMI_PRS_bins = recode(BMI_PRS_bins, 
                               `(-3.46,-1.02]` = "Low genetic risk", 
                               `(-1.02,1.03]` = "Moderate genetic risk", 
                               `(1.03,3.25]` = "High genetic risk"),
         T2D_fromEUR_PRS_bins = cut(T2D_fromEUR_PRS, breaks = c(min(T2D_fromEUR_PRS, na.rm = T), -0.9377243, 0.9407353, max(T2D_fromEUR_PRS, na.rm = T))),
         T2D_fromEUR_PRS_bins = recode(T2D_fromEUR_PRS_bins, 
                                       `(-3.34,-0.938]` = "Low genetic risk", 
                                       `(-0.938,0.941]` = "Moderate genetic risk", 
                                       `(0.941,3.2]` = "High genetic risk"),
         
         MDD_PRS_bins = cut(MDD_PRS, breaks = c(min(MDD_PRS, na.rm = T), -0.8940908, 0.8762605, max(MDD_PRS, na.rm = T))),
         MDD_PRS_bins = recode(MDD_PRS_bins,
                               `(-3.29,-0.894]` = "Low genetic risk", 
                               `(-0.894,0.876]` = "Moderate genetic risk", 
                               `(0.876,3.28]` = "High genetic risk"),
         
         newCDG2_PRS_bins = cut(newCDG2_PRS, breaks = c(min(newCDG2_PRS, na.rm = T), -0.762678, 0.7879327, max(newCDG2_PRS, na.rm = T))),
         newCDG2_PRS_bins = recode(newCDG2_PRS_bins,
                                   `(-2.48,-0.763]` = "Low genetic risk", 
                                   `(-0.763,0.788]` = "Moderate genetic risk", 
                                   `(0.788,2.96]` = "High genetic risk"),
         
         PTSD_fromEUR_PRS_bins = cut(PTSD_fromEUR_PRS, breaks = c(min(PTSD_fromEUR_PRS, na.rm = T), -0.9581097, 0.9490422, max(PTSD_fromEUR_PRS, na.rm = T))),
         PTSD_fromEUR_PRS_bins = recode(PTSD_fromEUR_PRS_bins,
                                        `(-3.38,-0.958]` = "Low genetic risk", 
                                        `(-0.958,0.949]` = "Moderate genetic risk", 
                                        `(0.949,3.49]` = "High genetic risk")
         )


# Diabetes
fit_diabetes <- lm(allostatic_load ~ exposome_score_1y*T2D_fromEUR_PRS_bins, data = dataset_main_eur %>% filter(genetic_afr == 0))
summary(fit_diabetes)
fit_diabetes_df <- ggpredict(fit_diabetes, terms = c("exposome_score_1y", "T2D_fromEUR_PRS_bins"))

plot(fit_diabetes_df) +
  labs(x = "Exposomic Score",
       y = "Allostatic Load",
       title = "Diabetes PRS"
       # colour = "",
  ) +
  scale_color_manual(values = c("#D81159", "#0496FF", "#3EC300")) +
  scale_fill_manual(values = c("#D81159", "#0496FF", "#3EC300")) +
  theme_bw() +
  theme(axis.text.x = element_text(size = 18, color = "black", face = "bold"),
        axis.text.y = element_text(size = 18, color = "black", face = "bold"),
        axis.title.y = element_text(size = 20, face = "bold"),
        axis.title.x = element_text(size = 20, face = "bold"),
        axis.ticks=element_line(size = 0.5),
        legend.title = element_blank(),
        legend.text = element_text(size = 17),
        legend.position = c(0.3, 0.85),
        plot.title = element_text(size = 22, hjust = 0.5)) +
  guides(color = guide_legend(nrow = 3))
ggsave("../plots/interaction_exposome_T2D_fromEUR_PRS.pdf")


# Major Depressive Disorder (MDD) # EUR
fit_MDD <- lm(allostatic_load ~ exposome_score_1y*MDD_PRS_bins, data = dataset_main_eur %>% filter(genetic_afr == 0))
summary(fit_MDD)
fit_MDD_df <- ggpredict(fit_MDD, terms = c("exposome_score_1y", "MDD_PRS_bins"))

plot(fit_MDD_df) +
  labs(x = "Exposomic Score",
       y = "Allostatic Load",
       title = "Major Depressive Disorder PRS"
       # colour = "Major Depressive Disorder PRS",
  ) +
  scale_color_manual(values = c("#FE4A49", "#0D21A1", "#06BA63")) +
  scale_fill_manual(values = c("#FE4A49", "#0D21A1", "#06BA63")) +
  theme_bw() +
  theme(axis.text.x = element_text(size = 18, color = "black", face = "bold"),
        axis.text.y = element_text(size = 18, color = "black", face = "bold"),
        axis.title.y = element_text(size = 20, face = "bold"),
        axis.title.x = element_text(size = 20, face = "bold"),
        axis.ticks=element_line(size = 0.5),
        legend.title = element_blank(),
        legend.text = element_text(size = 17),
        legend.position = c(0.3, 0.85),
        plot.title = element_text(size = 22, hjust = 0.5)) +
  guides(color = guide_legend(nrow = 3))
ggsave("../plots/interaction_exposome_MDD_PRS.pdf", dpi = 620)
```


# For the EUR/AFR ancestry kids - tabulation of their race and ethnicity (n/% White, n/% Black, n/% Hispanic)
```{r}
CreateTableOne(
  data = dataset_main,
  strata = "genetic_afr",
  vars = c("race_white", "race_black", "ethnicity_hisp", "sex_br"),
  factorVars = c("race_white", "race_black", "ethnicity_hisp", "sex_br"),
  includeNA = F,
  addOverall = F
)
```






